services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_DIR=1
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped

  app2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_DIR=2
    ports:
      - "8502:8501"
    env_file:
      - .env
    restart: unless-stopped

  app3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_DIR=3
    ports:
      - "8503:8501"
    env_file:
      - .env
    restart: unless-stopped

  app4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_DIR=4
    ports:
      - "8504:8501"
    env_file:
      - .env
    restart: unless-stopped


